### ISSUE TITLE
Project Binary

### ISSUE THREAD

**Issue by KaranDagar** [SoftwareEngineeringToolDemos/ICSE-2013-NavClus#1]
Project binary is not present.

**Comment by akottal** [comment]
Isn't the plugin the binary in this case?

**Comment by KaranDagar** [comment]
Ok, I am satisfied by your response. I am closing this issue.
Thanks,
Karan

**Comment by KaranDagar** [comment]
Ok, I am satisfied by your response. Closing this issue.
Thanks,
Karan
