### ISSUE TITLE
VM license incomplete

### ISSUE THREAD

**Issue by KaranDagar** [SoftwareEngineeringToolDemos/ICSE-2013-NavClus#10]
It appears that VM license file is incomplete. Nothing is mentioned in Section 2 "Grant of Rights".
Thanks,
Karan

**Comment by akottal** [comment]
There are 4 sub-sections a,b,c,d in the "Grant of Rights" section. Can you please elaborate on this issue?

**Comment by akottal** [comment]
Closing this issue as there hasn't been any response.
