### ISSUE TITLE
Regarding the README.md

### ISSUE THREAD

**Issue by KaranDagar** [SoftwareEngineeringToolDemos/ICSE-2013-NavClus#2]
Please state after the Contact us section " Acknowledgement by your name" . This way a quick glance can easily let the reader know that this is not the original repository.
Adding an explicit "Disclaimer:" will make reading more clear

**Comment by akottal** [comment]
The content in the README.md till the horizontal line is the directly taken from the parent repo from which this has been forked. Can you please elaborate on what you meant by "Acknowledgement by your name", so that I can make the necessary changes?

**Comment by KaranDagar** [comment]
I am assigning it to myself. Don't worry.
