### ISSUE TITLE
README - binary

### ISSUE THREAD

**Issue by KaranDagar** [SoftwareEngineeringToolDemos/ICSE-2013-NavClus#3]
README.md is not linked to the binary.

**Comment by akottal** [comment]
As mentioned in the comment to other issue, wouldn't the plugin be the binary? And the README.md has a link to the plugin. Please let me know if I am missing something.

**Comment by KaranDagar** [comment]
ok. I am satisfied by your response. Closing this issue.

Thanks,
Karan
