### ISSUE TITLE
No sound in VM

### ISSUE THREAD

**Issue by KaranDagar** [SoftwareEngineeringToolDemos/ICSE-2013-NavClus#9]
There was no sound in the VM. When I opened the youtube link I could see the video but couldn't here anything that was being said. 
When I opened it in my desktop, video does have sound but somehow in VM there is no sound.

Thanks,
Karan

**Comment by akottal** [comment]
Professor said not having audio is fine as long as video is clear enough.

https://piazza.com/class/idk9st8m26917?cid=180

**Comment by akottal** [comment]
Closing this issue on the above note.
